services:
  postgres:
    container_name: atlas_postgres
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${VARIABLE2:-password}
      - POSTGRES_DB=${POSTGRES_DB:-atlas}
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# volumes:
#   postgres:

networks:
  postgres:
    driver: bridge
