---
# https://github.com/DavidAnson/markdownlint

# Rules by ID
MD013:
  line_length: 1000 # Line length 80 is far to short
MD26: false         # Allow punctuation at the end of headers

# Rules by Tag
blank_lines: false  # Allow blank lines
